services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: huenets-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: huenets-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:4000
      - NODE_ENV=production
    command: npm start
    depends_on:
      - backend
